# 1. Скачиваем репозиторий с вашим stardict.zip
   #   - name: Checkout repository
    #    uses: actions/checkout@v4

      # 2. Распаковываем архив
      - name: Unpack ZIP
        run: |
          # unzip -o распакует stardict.zip в папку stardict_src
          unzip -o ApresyanEnRu.dictionary.zip -d dict_src
